server:
  port: 9020
  
eureka:
  instance:
    hostname: localhost
    
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: team-service
          uri: lb://team-service
          predicates:
            - Path=/api/v1/team/**
           
            
        - id: player-service
          uri: lb://player-service
          predicates:
            - Path=/api/v1/player/**                                    