server:
  port: 9020
  
eureka:
  instance:
    hostname: localhost
    
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: college-service
          uri: lb://college-service
          predicates:
            - Path=/api/v1/college/**
           
            
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/api/v1/student/**                                    